#!/usr/bin/python3
import os
import argparse


            
if __name__ == '__main__':
    p = argparse.ArgumentParser(usage="usage: odmax [options], type odmax --help for options"
)
    p.add_argument('-i', '--infile',
                   help='Input video file, compatible with OpenCV2')
    p.add_argument('-o', '--outpath',
                   help='Directory to write output files.', default=".")
    p.add_argument('-p', '--prefix',
                   help='Prefix to use for written image files', default="still")

    args = p.parse_args()
    # Do something
    print(f"Your arguments are {args}")